### ISSUE TITLE
Create tables to store the phone pressures

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-server#340]
# Description
É necessário criar uma estrutura para persistir as solicitações de pressão por telefone e suas alterações de estado.

# Tasks
- [x] Criar tabela para persistir as solicitações de pressão por telefone
- [x] Criar tabela para persistir as alterações de estado da chamada
- [x] Criar função no postgraphql para salvar as solicitações de pressão por telefone
- [x] Criar trigger de notify a cada novo insert na tabela de solicitações de chamada
- [x] Relacionar tabela de chamadas do twilio com widget
- [x] Criar função para observar as alterações de status das ligações

**Comment by gabrielrtakeda** [comment]
@devton, tu consegue dar um help nessa issue? Cheguei a criar as tabelas e a uma função no postgraphql pra criar uma nova solicitação de chamada mas, estou enfrentando um problema de permissão.. Segue abaixo o que consegui fazer até aqui:

### Ruby on Rails
**tabela `twilio_calls`**
```ruby
class CreateTwilioCalls < ActiveRecord::Migration
  def change
    create_table :twilio_calls do |t|
      t.references :activist
      t.text :from, null: false
      t.text :to, null: false
      t.text :body, null: false

      t.timestamps null: false
    end
  end
end
```

**tabela `twilio_call_transitions`**
```ruby
class CreateTwilioCallTransitions < ActiveRecord::Migration
  def change
    create_table :twilio_call_transitions do |t|
      t.references :twilio_call
      t.text :status, null: false
      t.text :duration, null: false

      t.timestamps null: false
    end
  end
end
```

### PostgreSQL
**type `postgraphql.twilio_call`**
```sql
create type postgraphql.twilio_call as (
  activist_id integer,
  "from" text,
  "to" text,
  body text
);
drop type postgraphql.twilio_call;
```

**function `postgraphql.create_twilio_call`**
```sql
create or replace function postgraphql.create_twilio_call (call postgraphql.twilio_call)
  returns public.twilio_calls language plpgsql AS $$
    declare
      twilio_calls public.twilio_calls;
    begin
      insert into public.twilio_calls
          (
            activist_id,
            "from",
            "to",
            body,
            created_at,
            updated_at
          ) values (
            coalesce(call.activist_id, null),
            call.from,
            call.to,
            call.body,
            now(),
            now()
          )
          returning * into twilio_calls;

          return twilio_calls;
    end;
  $$;
};
drop function postgraphql.create_twilio_call (call postgraphql.twilio_call);
```

**Observação:** eu tentei dar **grant** na `sequence` como você havia comentado comigo no slack mas, infelizmente quando faço requisição com a role **anonymous**, continuo tendo problema com a permissão...

**achando o nome da `sequence`**
```sql
select relname from pg_class c where relname ~* 'twilio_calls';
```

**resultado**
```
twilio_calls
twilio_calls_pkey
twilio_calls_id_seq <~ essa aqui
```

### GraphQL
**mutation `createTwilioCall`**
```graphql
mutation {
  createTwilioCall(input: {
    call: {
      activistId: 1
      from: "+551199999999"
      to: "+5511999999999"
      body: "Hello Twilio"
    }
  }) {
    twilioCalls {
      id,
      activistId,
      from
      to
      body
      createdAt
      updatedAt
    }
  }
}
```

**Comment by gabrielrtakeda** [comment]
@devton, rodei os seguintes **grant**s pra role `anonymous` e aparentemente funcionou mas, sinto que não é a melhor coisa a se fazer.. segue:

```sql
grant usage on schema public to anonymous;
grant insert on public.twilio_calls to anonymous;
```

**Comment by gabrielrtakeda** [comment]
Rebase 👇
