### ISSUE TITLE
Create tables to store the BONDE's communities twilio configurations

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-server#350]
# Description
É necessário que seja criada uma tabela no banco de dados que, ficará responsável por armazenar os dados de acesso a API do Twilio. Permitindo assim, que seja possível a configuração de tais dados de acordo com a respectiva comunidade. Ou seja, à partir desta funcionalidade, a responsabilidade em arcar com os gastos de ligação pelo Twilio, será respectivamente de cada comunidade que criar uma mobilização de pressão por telefone.

# Tasks
- [x] Criar tabela `twilio_configurations`
- [x] Criar view no postgraphql da tabela `twilio_configurations`
- [x] Criar função no postgraphql para **inserir** uma nova configuração
- [x] Criar função no postgraphql para **atualizar** uma configuração
