### ISSUE TITLE
Save bot mass message campaign

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde-server#381]
# Related external repository issues
- Bot mass message campaign nossas/bonde-client#885
- Save bot mass message campaign nossas/bonde-bot#69

# Description
É necessário que seja salva a campanha de envio de mensagem em massa para os usuários que interagiram com o bot, como forma de manter o histórico.

### Sugestão de estrutura das tabelas

**facebook_bot_campaigns**
```ruby
t.references :facebook_bot_configuration, index: true, foreign_key: true, null: false
t.jsonb :message_payload, null: false

t.timestamps null: false
```

**facebook_bot_campaign_activists**
```ruby
t.references :facebook_bot_campaign, index: true, foreign_key: true, null: false
t.references :facebook_bot_activist, index: true, foreign_key: true, null: false
t.boolean :received, null: false, default: false

t.timestamps null: false
```

# Tasks

**Layout de settings page**
- Tasks migradas para a issue ~> nossas/bonde-client#885

**Etapa de segmentação por campanha**
- Tasks migradas para a issue ~> nossas/bonde-client#885

**Geração de histórico de campanhas**
- [x] Criar stack de tabelas
- [x] Gerar um novo registro de campanha no recebimento da requisição de enfileiramento
- [x] Gerar um novo registro em `facebook_bot_campaign_activists` para cada ativista impactado
- ~Fazer com que worker de processamento da fila atualize o status de envio da mensagem~ ~> nossas/bonde-bot#69

**Filtro de exclusão de usuários por campanha**
- [x] Criar function para filtrar os usuários que NÃO receberam as campanhas selecionadas (e.g. filtro de mensagem e data segmenta 13k usuários, ao selecionar uma campanha com 10k usuários, o resultado da exclusão será de 3k usuários selecionados). **Sugestão:** Receber `array` de `id`s da tabela `public.facebook_bot_campaigns`
- [x] Criar function de "união" dos ativistas selecionados através dos filtros básicos + ativistas impactados pelas campanhas desejadas
- [x] Criar function de "união" dos ativistas filtrados que NÃO receberam as campanhas selecionadas + ativistas impactados pelas campanhas desejadas

**Log de envio de mensagem individual**
- [x] GraphQL query para listar os ativistas impactados de uma determinada campanha
- [x] GraphQL mutation para atualizar status do envio da mensagem individual para o usuário

**Comment by gabrielrtakeda** [comment]
@devton e @lpirola, consegui criar aqui todas as funções necessárias para que o filtro de campanha de envio de mensagem em massa seja feito corretamente... Atualizei a lista de tasks da seção de **Filtro de exclusão de usuários por campanha** com as tasks adicionais que encontrei durante o desenvolvimento do filtro de exclusão...

@devton, acabou que nem precisei fazer uso da coluna computada mencionada por você na reunião de planning... Um ligeiro `LEFT JOIN` resolveu meu problema... Vou atualizar a seção de **How to test** com as informações de teste das funções:
- `get_facebook_activists_by_campaigns_exclusion`
- `get_facebook_activists_by_campaigns_inclusion`
- `get_facebook_activists_by_campaigns_both_inclusion_exclusion`
- `get_facebook_activists_strategy` (as funções supracitadas estão abstraídas nessa function)

**Comment by lpirola** [comment]
maravilha @gabrielrtakeda aguardamos para fazer testes.
